### ISSUE TITLE
GIF in README.md is quite old

### ISSUE THREAD

**Issue by yashovardhanagrawal** [coala/coala-html#141]
the GIF in README.md is old and should be replaced by the new version of coala-html.

Also, it can replace the report image in README.md

**Comment by Lavenderjiang** [comment]
I'm having this error... Any help would be appreciated! http://gph.is/2jmuE6q

**Comment by Lavenderjiang** [comment]
I fixed the bower issue by changing the ownership of files in .config and .cache. Though I am able to launch the website now, I keep getting the error message "The requested section '/users/lavender/desktop/coala-html/test' is not existent. Thus it cannot be executed."

**Comment by jayvdb** [comment]
Unassigned due to inactivity.

**Comment by fireballpoint1** [comment]
@yashovardhanagrawal so we want to just repeat the same process for the updated coala ? if yes, can I work on this issue

**Comment by fireballpoint1** [comment]
I suggest adding a video link instead of a GIF since it's confusing to track the progress in a GIF and you can't go back if you missed a moment, you need to wait for it to repeat all the way and with such a large GIF it is inconvenient

**Comment by yashovardhan** [comment]
The advantage of having a GIF file will that it is shown in the README.md directly when someone opens the GitHub repo. Having a video link would not solve this purpose. GIF just improves the overall quality of the README this way.

**Comment by fireballpoint1** [comment]
At the moment it appears as just a link though.

**Comment by KVGarg** [comment]
Hi @yashovardhanagrawal , can I work upon this issue ?

**Comment by KVGarg** [comment]
> I suggest adding a video link instead of a GIF since it's confusing to track the progress in a GIF and you can't go back if you missed a moment, you need to wait for it to repeat all the way and with such a large GIF it is inconvenient

In GIF, we are executing only one instruction in terminal i.e. to tun coala-html on a project. After updating the `Build & development` instructions section in the new PR, I think there is no need of video now. Also, If we add video then we have to add it for atlesast 3 OSX (Windows, Linux and Mac). I think GIF will work here

**Comment by yashovardhan** [comment]
sure go for it, ask a maintainer on gitter to assign you this issue

**Comment by KVGarg** [comment]
Should I create GIF based on coala repository or on any of my project? SInce coala repo will not show any errors, so I was thinking to run on my personal project

**Comment by KVGarg** [comment]
@yashovardhanagrawal Should I create GIF based on coala repository or on any of my project? SInce coala repo will not show any errors, so I was thinking to run on my personal project
